# Generated by Django 5.1.4 on 2024-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactedCustomers',
            fields=[
                ('id', models.AutoField(help_text='Unique reference for request from customer or user who wanted to contact us', primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer name who requested to contact us', max_length=254)),
                ('customer_email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('customer_message', models.TextField()),
                ('contacted_date', models.DateTimeField(auto_now=True, help_text='DataTime of the customer request to contact us')),
                ('is_responded', models.BooleanField(default=False, help_text='It shows whether we responded back on the customer request')),
                ('responded_date', models.DateTimeField(help_text='Date on which we responded back to the customer')),
            ],
        ),
    ]
