# Generated by Django 5.1.4 on 2024-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedcustomers',
            name='customer_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactedcustomers',
            name='responded_date',
            field=models.DateTimeField(blank=True, help_text='Date on which we responded back to the customer'),
        ),
    ]
