# Generated by Django 5.1.4 on 2024-12-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapp', '0002_alter_contactedcustomers_customer_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactedcustomers',
            name='responded_date',
            field=models.DateTimeField(blank=True, help_text='Date on which we responded back to the customer', null=True),
        ),
    ]
